server:
  port: 9000
spring:
  application:
    name: ad-gateway
eureka:
  client:
    service-url:
       defaultZone: http://server1:8000/eureka/

zuul:
  prefix: /hyczzz
  routes:
    sponsor:
      path: /ad-sponsor/**
      serviceId: eureke-client-ad-sponsor
      strip-prefix: false